apiVersion: v1
kind: Namespace
metadata:
  name: black-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: black-app
  namespace: black-ns
  labels:
    app: black-app
spec:
  selector:
    matchLabels:
      app: black-app
  replicas: 2
  template:
    metadata:
      labels:
        app: black-app
    spec:
      containers:
      - name: black-container
        image: public.ecr.aws/e1x6y8e1/black:latest
        ports:
            - containerPort: 80
        resources:
          limits:
            memory: "100Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: black-ns
  name: black-service
  labels:
    app: black-app
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /index.html
spec:
  type: ClusterIP
  selector:
    app: black-app
  ports:
    - port: 80
      targetPort: 80
