apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sqs-consumer-vpa
  namespace: vpa-sqs-scaling-demo
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sqs-consumer
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: sqs-consumer
      minAllowed:
        cpu: 100m
        memory: 64Mi
      maxAllowed:
        cpu: 2000m
        memory: 2Gi
      controlledResources: ["cpu", "memory"]
