apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: snapshot-controller
commonLabels:
  app: snapshot-controller
resources:
  - rbac-snapshot-controller.yaml
  - setup-snapshot-controller.yaml
