apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restored-vmware-csi-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vmware-sc
  resources:
    requests:
      storage: 4Gi
  dataSource:
    name: vmware-csi-volume-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io