apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
  namespace: msk-microbatch-demo
type: Opaque
stringData:
  username: "kafka-user"
  password: "REPLACE_WITH_ACTUAL_PASSWORD"
  bootstrap-servers: "REPLACE_WITH_BOOTSTRAP_SERVERS"
