apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmware-csi-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vmware-sc
  resources:
    requests:
      storage: 4Gi