apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: {{ .Values.gitOpsRepo.url | quote }}
      targetRevision: {{ .Values.gitOpsRepo.branch | quote }}
      ref: values
    - repoURL: https://github.com/BerriAI/litellm
      targetRevision: v1.55.10
      path: deploy/charts/litellm-helm
      helm:
        releaseName: litellm
        valueFiles:
          - {{ printf "$values/%s/gitops/addons/litellm/values.yaml" .Values.basePath | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.litellm | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
