apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adot-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    path: {{ .Values.gitops.basePath }}/gitops/addons/adot-collector
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
