apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bifrost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: bifrost
    repoURL: https://maximhq.github.io/bifrost/helm-charts
    targetRevision: "2.*"
    helm:
      releaseName: bifrost
      valuesObject:
        image:
          tag: "v1.5.0"
        serviceAccount:
          create: true
          name: bifrost
        env:
          - name: AWS_REGION
            value: "{{ .Values.region }}"
        plugins:
          governance:
            enabled: true
            config:
              is_vk_mandatory: false
          otel:
            enabled: true
            version: 1
            config:
              service_name: "bifrost"
              collector_url: "otel-collector-opentelemetry-collector.{{ .Values.namespaces.observability }}:4317"
              trace_type: "genai_extension"
              protocol: "grpc"
              insecure: true
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.agents }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
