apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bifrost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: bifrost
    repoURL: https://maximhq.github.io/bifrost/helm-charts
    targetRevision: "2.*"
    helm:
      releaseName: bifrost
      valuesObject:
        image:
          tag: "v1.5.0"
        serviceAccount:
          create: true
          name: bifrost
        env:
          - name: AWS_REGION
            value: "{{ .Values.region }}"
        config:
          enforceAuthOnInference: false
        plugins:
          governance:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.agents }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
