apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: agentcore-code-interpreter
spec:
  schema:
    apiVersion: kro.run/v1alpha1
    kind: AgentCoreCodeInterpreter
    spec:
      name:
        type: string
      namespace:
        type: string
  resources:
    - id: codeinterpreter
      apiVersion: bedrockagentcorecontrol.services.k8s.aws/v1alpha1
      kind: CodeInterpreter
      metadata:
        name: ${schema.spec.name}
        namespace: ${schema.spec.namespace}
      spec:
        name: ${schema.spec.name}
    - id: secret
      apiVersion: v1
      kind: Secret
      metadata:
        name: "${schema.spec.name}-code-interpreter-outputs"
        namespace: ${schema.spec.namespace}
      stringData:
        id: ${codeinterpreter.status.id}
