apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: snapshot-enabler
commonLabels:
  app: snapshot-enabler
resources:
  - snapshot-enabler-role.yaml
  - snapshot-enabler-script.yaml
  - snapshot-enabler-job.yaml