apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-csi-snapshot-components-role
  namespace: vmware-system-csi
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "services", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-csi-snapshot-components-rolebinding
  namespace: vmware-system-csi
subjects:
  - kind: ServiceAccount
    name: default
    namespace: vmware-system-csi
roleRef:
  kind: Role
  name: deploy-csi-snapshot-components-role
  apiGroup: rbac.authorization.k8s.io