apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-csi-snapshot-components-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "services", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-csi-snapshot-components-rolebinding
  namespace: vmware-system-csi
subjects:
  - kind: ServiceAccount
    name: default
    namespace: vmware-system-csi
roleRef:
  kind: ClusterRole
  name: deploy-csi-snapshot-components-role
  apiGroup: rbac.authorization.k8s.io