apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: storage-tester
commonLabels:
  app: storage-tester
resources:
  - test-app-job.yaml
  - snapshot.yaml
  - restore-test-pod.yaml
  