---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restored-vmware-csi-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vmware-sc
  resources:
    requests:
      storage: 4Gi
  dataSource:
    name: vmware-csi-volume-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: app-restore
  namespace: default
  labels:
    app: snapshot-restore-tester
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: restored-vmware-csi-claim
  