---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: vmware-csi-snapshotclass
driver: csi.vsphere.vmware.com
deletionPolicy: Delete
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: vmware-csi-volume-snapshot
  namespace: default
spec:
  volumeSnapshotClassName: vmware-csi-snapshotclass
  source:
    persistentVolumeClaimName: vmware-csi-claim