---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmware-csi-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vmware-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: app
  namespace: default
spec:
  backoffLimit: 3 
  template:
    spec:
      containers:
      - name: app
        image: centos
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
      restartPolicy: OnFailure
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: vmware-csi-claim