apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vmware-csi-driver
  namespace: flux-system
spec:
  path: "./vmware-csi-driver-gitops/vmware-csi-driver"
  sourceRef:
    kind: GitRepository
    name: vmware-csi
    namespace: flux-system
  interval: 1m0s
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-enabler
  namespace: flux-system
spec:
  dependsOn:
    - name: vmware-csi-driver
  path: "./vmware-csi-driver-gitops/snapshot-enabler"
  sourceRef:
    kind: GitRepository
    name: vmware-csi
    namespace: flux-system
  interval: 1m0s
  prune: true
  healthChecks: 
  - apiVersion: batch/v1
    kind: Job
    name: deploy-csi-snapshot-components-job
    namespace: kube-system
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-tester
  namespace: flux-system
spec:
  dependsOn:
    - name: snapshot-enabler
  path: "./vmware-csi-driver-gitops/storage-tester"
  sourceRef:
    kind: GitRepository
    name: vmware-csi
    namespace: flux-system
  interval: 1m0s
  prune: true