apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: vmware-csi-driver
commonLabels:
  app: vmware-csi-driver
resources:
  - namespace.yaml
  - vsphere-external-secrets.yaml
  - vsphere-cloud-controller-manager.yaml
  - vmware-csi-driver.yaml
  - vmware-sc.yaml