---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vmware-csi-kustomization
  namespace: flux-system
  labels:
    app: vmware-csi-driver
spec:
  interval: 1m0s
  path: ./vmware-csi-driver/vmware-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: blog-repo
