apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${EKSA_REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: ${EKSA_ES_SERVICE_ACCOUNT}
            namespace: ${EKSA_ADOT_NAMESPACE}