apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eksa-externalsecret
  namespace: grafana-operator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
  data:
  - secretKey: GF_SECURITY_ADMIN_APIKEY
    remoteRef:
      key: ${GO_API_KEY_SECRET_NAME}